name: Build

# on events
on: push

jobs:
  build:
    strategy:
      matrix:
        target: [ 
          { os: darwin, arch: amd64 }, 
          { os: darwin, arch: arm64 }, 
          { os: linux, arch: arm64 } ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: ${{ matrix.target.os }} ${{ matrix.target.arch }}
      env: 
        GOOS: ${{ matrix.target.os }} 
        GOARCH: ${{ matrix.target.arch }}
      run: |
        go build -buildmode exe -o revent-${{ matrix.target.os }}-${{ matrix.target.arch }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: revent-*
        retention-days: 5
            
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: data

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: revent-* 
